# This file was created under the guidance of the tutorial:
# https://wiki.ros.org/navigation/Tutorials/RobotSetup#Costmap_Configuration_.28local_costmap.29_.26_.28global_costmap.29

# The radius of the quadrotor is around 0.5 meters

robot_radius: 0.9

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.9  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true




